### ISSUE TITLE
Looks great - iSmartGate support?

### ISSUE THREAD

**Issue by shanelord01** [mgroeninger/Hubitat-gogogate2#1]
Hi,

**UPDATE 2** Hi mate - I've done some very quick and dirty hacks to the files and have it working for me now - forked here: https://github.com/scrytch/Hubitat-iSmartGate 

This looks great but wondering if it will work with the new iSmartGate from the same manufacturer (Remsol) ?

At the moment I install the parent driver, fill in the details etc it doesn't create the child devices.

Debug log looks like this - note the temperature sensor error is when I hit the "Recreate child devices" button in the parent driver. 

**UPDATE 1**: I have wired door sensors not wireless - so they don't support temperature or battery - how can I remove this code?

`dev:4232019-09-06 11:45:49.644 am debugGoGoGate2 -- Raw status info is: '{"1":"0","2":"0","3":"0"}'

dev:4232019-09-06 11:45:49.643 am debugGoGoGate2 -- Response from GoGoGate 2 was: {"1":"0","2":"0","3":"0"}

dev:4232019-09-06 11:45:49.537 am debugGoGoGate2 -- Light status is off
dev:4232019-09-06 11:45:49.534 am debugGoGoGate2 -- Response from GoGoGate 2 was: 0
dev:4232019-09-06 11:45:49.464 am debugGoGoGate2 -- Refresh tick
dev:4232019-09-06 11:45:47.823 am warnGoGoGate2 -- Invalid sensor temperature of -1000.0 °C .

dev:4232019-09-06 11:45:47.821 am debugGoGoGate2 -- Raw sensor info is: ["-1000000","-1000000"]

dev:4232019-09-06 11:45:47.812 am debugGoGoGate2 -- Response from GoGoGate 2 was: ["-1000000","-1000000"]

dev:4232019-09-06 11:45:47.770 am warnGoGoGate2 -- Invalid sensor temperature of -1000.0 °C .

dev:4232019-09-06 11:45:47.769 am debugGoGoGate2 -- Raw sensor info is: ["-1000000","-1000000"]

dev:4232019-09-06 11:45:47.767 am debugGoGoGate2 -- Response from GoGoGate 2 was: ["-1000000","-1000000"]

dev:4232019-09-06 11:45:47.709 am warnGoGoGate2 -- Invalid sensor temperature of -1000.0 °C .

dev:4232019-09-06 11:45:47.706 am debugGoGoGate2 -- Raw sensor info is: ["-1000000","-1000000"]

dev:4232019-09-06 11:45:47.705 am debugGoGoGate2 -- Response from GoGoGate 2 was: ["-1000000","-1000000"]

dev:4232019-09-06 11:45:47.650 am debugGoGoGate2 -- Parent deleteChildren
dev:4232019-09-06 11:45:47.649 am debugGoGoGate2 -- Parent recreateChildDevices`

Thanks,
Shane.

**Comment by mgroeninger** [comment]
Hi Shane,
  Sorry, I didn't get notified about this issue!  I apologize. I"m glad you got it working!
Matt
