### ISSUE TITLE
Unable to Import Parent Driver in Latest Hubitat

### ISSUE THREAD

**Issue by CodyRWhite** [mgroeninger/Hubitat-gogogate2#2]
Hubitat Version : 2.3.4.119

Error on Import
No signature of method: Script1.definition() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:Environmental Comfort, namespace:env_comfort, author:Matt Groeninger, ...]] on line 19

Not quite sure what to do.

**Comment by mgroeninger** [comment]
Hi Cody,
  Sorry about this, but it looks like I uploaded the incorrect contents of a file to the parent driver.  Let me figure out what I was trying to do so I can fix it and I'll let you know when I get the driver sorted out.
Matt

**Comment by mgroeninger** [comment]
Hi Cody,
  I've commited the proper file contents to the Parent driver. Sorry about that.
Please let me know if it works now.
Thanks,
Matt

**Comment by mgroeninger** [comment]
I believe the parent driver is correct now, so I'm closing this issue.  Thanks!
